//! A in-memory representation of the AST
//!
//! This is automatically generated from the ASDL file

use super::{Ident, Span, Spanned};
use super::constants::Constant;

use educe::Educe;

// Original file was automatically generated by asdl/rust.py.

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub enum Mod<'a> {
    Module {
        body: &'a [Stmt<'a>],
        type_ignores: &'a [TypeIgnore<'a>],
    },
    Interactive {
        body: &'a [Stmt<'a>],

    },
    Expression {
        body: &'a Expr<'a>,

    },
    FunctionType {
        argtypes: &'a [Expr<'a>],
        returns: &'a Expr<'a>,

    },
}
#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub enum Stmt<'a> {
    FunctionDef {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        name: Ident<'a>,
        args: &'a Arguments<'a>,
        body: &'a [Stmt<'a>],
        decorator_list: &'a [Expr<'a>],
        returns: Option<&'a Expr<'a>>,
        type_comment: Option<&'a str>,

    },
    AsyncFunctionDef {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        name: Ident<'a>,
        args: &'a Arguments<'a>,
        body: &'a [Stmt<'a>],
        decorator_list: &'a [Expr<'a>],
        returns: Option<&'a Expr<'a>>,
        type_comment: Option<&'a str>,

    },
    ClassDef {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        name: Ident<'a>,
        bases: &'a [Expr<'a>],
        keywords: &'a [Keyword<'a>],
        body: &'a [Stmt<'a>],
        decorator_list: &'a [Expr<'a>],

    },
    Return {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: Option<&'a Expr<'a>>,

    },
    Delete {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        targets: &'a [Expr<'a>],
    },
    Assign {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        targets: &'a [Expr<'a>],
        value: &'a Expr<'a>,
        type_comment: Option<&'a str>,
    },
    AugAssign {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        target: &'a Expr<'a>,
        op: Operator,
        value: &'a Expr<'a>,

    },
    AnnAssign {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        target: &'a Expr<'a>,
        annotation: &'a Expr<'a>,
        value: Option<&'a Expr<'a>>,
        simple: bool,
    },
    For {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        target: &'a Expr<'a>,
        iter: &'a Expr<'a>,
        body: &'a [Stmt<'a>],
        orelse: &'a [Stmt<'a>],
        type_comment: Option<&'a str>,
    },
    AsyncFor {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        target: &'a Expr<'a>,
        iter: &'a Expr<'a>,
        body: &'a [Stmt<'a>],
        orelse: &'a [Stmt<'a>],
        type_comment: Option<&'a str>,
    },
    While {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        test: &'a Expr<'a>,
        body: &'a [Stmt<'a>],
        orelse: &'a [Stmt<'a>],
    },
    If {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        test: &'a Expr<'a>,
        body: &'a [Stmt<'a>],
        orelse: &'a [Stmt<'a>],
    },
    With {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        items: &'a [WithItem<'a>],
        body: &'a [Stmt<'a>],
        type_comment: Option<&'a str>,
    },
    AsyncWith {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        items: &'a [Withitem<'a>],
        body: &'a [Stmt<'a>],
        type_comment: Option<&'a str>,

    },
    Match {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        subject: &'a Expr<'a>,
        cases: &'a [MatchCase<'a>],
    },
    Raise {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        exc: Option<&'a Expr<'a>>,
        cause: Option<&'a Expr<'a>>,

    },
    Try {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        body: &'a [Stmt<'a>],
        handlers: &'a [Excepthandler<'a>],
        orelse: &'a [Stmt<'a>],
        finalbody: &'a [Stmt<'a>],
    },
    Assert {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        test: &'a Expr<'a>,
        msg: Option<&'a Expr<'a>>,

    },
    Import {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        names: &'a [Alias<'a>],
    },
    ImportFrom {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        module: Option<Ident<'a>>,
        names: &'a [Alias<'a>],
        level: Option<i32>,
    },
    Global {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        names: &'a [Ident<'a>],
    },
    Nonlocal {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        names: &'a [Ident<'a>],
    },
    Expr {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
    },
    Pass {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
    },
    Break {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
    },
    Continue {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
    },
}
impl<'a> Spanned for Stmt<'a> {
    fn span(&self) -> Span {
        match *self {
            Stmt::FunctionDef { span, .. } |
            Stmt::AsyncFunctionDef { span, .. } |
            Stmt::ClassDef { span, .. } |
            Stmt::Return { span, .. } |
            Stmt::Delete { span, .. } |
            Stmt::Assign { span, .. } |
            Stmt::AugAssign { span, .. } |
            Stmt::AnnAssign { span, .. } |
            Stmt::For { span, .. } |
            Stmt::AsyncFor { span, .. } |
            Stmt::While { span, .. } |
            Stmt::If { span, .. } |
            Stmt::With { span, .. } |
            Stmt::AsyncWith { span, .. } |
            Stmt::Match { span, .. } |
            Stmt::Raise { span, .. } |
            Stmt::Try { span, .. } |
            Stmt::Assert { span, .. } |
            Stmt::Import { span, .. } |
            Stmt::ImportFrom { span, .. } |
            Stmt::Global { span, .. } |
            Stmt::Nonlocal { span, .. } |
            Stmt::Expr { span, .. } |
            Stmt::Pass { span, .. } |
            Stmt::Break { span, .. } |
            Stmt::Continue { span, .. } => span,
        }
    }
}
#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub enum Expr<'a> {
    BoolOp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        op: Boolop,
        values: &'a [Expr],

    },
    NamedExpr {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        target: &'a Expr<'a>,
        value: &'a Expr<'a>,

    },
    BinOp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        left: &'a Expr<'a>,
        op: Operator,
        right: &'a Expr<'a>,

    },
    UnaryOp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        op: Unaryop,
        operand: &'a Expr<'a>,

    },
    Lambda {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        args: &'a Arguments<'a>,
        body: &'a Expr<'a>,

    },
    IfExp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        test: &'a Expr<'a>,
        body: &'a Expr<'a>,
        orelse: &'a Expr<'a>,

    },
    Dict {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elements: &'a [(Expr<'a>, Expr<'a>)],
    },
    Set {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elts: &'a [Expr<'a>],
    },
    ListComp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elt: &'a Expr<'a>,
        generators: &'a [Comprehension<'a>],
    },
    SetComp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elt: &'a Expr<'a>,
        generators: &'a [Comprehension<'a>],
    },
    DictComp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        key: &'a Expr<'a>,
        value: &'a Expr<'a>,
        generators: &'a [Comprehension<'a>],
    },
    GeneratorExp {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elt: &'a Expr<'a>,
        generators: &'a [Comprehension<'a>],
    },
    Await {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
    },
    Yield {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: Option<&'a Expr<'a>>,

    },
    YieldFrom {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,

    },
    Compare {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        left: &'a Expr<'a>,
        ops: &'a [Cmpop],
        comparators: &'a [Expr<'a>],
    },
    Call {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        func: &'a Expr<'a>,
        args: &'a [Expr<'a>],
        keywords: &'a [Keyword<'a>],
    },
    FormattedValue {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
        conversion: Option<char>,
        format_spec: Option<&'a Expr<'a>>,
    },
    JoinedStr {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        values: &'a [Expr<'a>],
    },
    Constant {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: Constant<'a>,
        kind: Option<String>,
    },
    Attribute {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
        attr: Ident<'a>,
        ctx: ExprContext,
    },
    Subscript {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
        slice: &'a Expr<'a>,
        ctx: ExprContext,
    },
    Starred {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
        ctx: ExprContext,
    },
    Name {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        id: Ident<'a>,
        ctx: ExprContext,
    },
    List {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elts: &'a [Expr<'a>],
        ctx: ExprContext,
    },
    Tuple {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        elts: &'a [Expr<'a>],
        ctx: ExprContext,
    },
    Slice {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        lower: Option<&'a Expr<'a>>,
        upper: Option<&'a Expr<'a>>,
        step: Option<&'a Expr<'a>>,
    },
}
impl<'a> Spanned for Expr<'a> {
    fn span(&self) -> Span {
        match *self {
            Expr::BoolOp { span, .. } |
            Expr::NamedExpr { span, .. } |
            Expr::BinOp { span, .. } |
            Expr::UnaryOp { span, .. } |
            Expr::Lambda { span, .. } |
            Expr::IfExp { span, .. } |
            Expr::Dict { span, .. } |
            Expr::Set { span, .. } |
            Expr::ListComp { span, .. } |
            Expr::SetComp { span, .. } |
            Expr::DictComp { span, .. } |
            Expr::GeneratorExp { span, .. } |
            Expr::Await { span, .. } |
            Expr::Yield { span, .. } |
            Expr::YieldFrom { span, .. } |
            Expr::Compare { span, .. } |
            Expr::Call { span, .. } |
            Expr::FormattedValue { span, .. } |
            Expr::JoinedStr { span, .. } |
            Expr::Constant { span, .. } |
            Expr::Attribute { span, .. } |
            Expr::Subscript { span, .. } |
            Expr::Starred { span, .. } |
            Expr::Name { span, .. } |
            Expr::List { span, .. } |
            Expr::Tuple { span, .. } |
            Expr::Slice { span, .. } => span,
        }
    }
}
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum ExprContext {
    Load=1,
    Store=2,
    Del=3,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Boolop {
    And=1,
    Or=2,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Operator {
    Add=1,
    Sub=2,
    Mult=3,
    MatMult=4,
    Div=5,
    Mod=6,
    Pow=7,
    LShift=8,
    RShift=9,
    BitOr=10,
    BitXor=11,
    BitAnd=12,
    FloorDiv=13,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Unaryop {
    Invert=1,
    Not=2,
    UAdd=3,
    USub=4,
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum Cmpop {
    Eq=1,
    NotEq=2,
    Lt=3,
    LtE=4,
    Gt=5,
    GtE=6,
    Is=7,
    IsNot=8,
    In=9,
    NotIn=10,
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct Comprehension<'a> {
    pub target: &'a Expr<'a>,
    pub iter: &'a Expr<'a>,
    pub ifs: &'a [Expr<'a>],
    pub is_async: bool,
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct ExceptHandler<'a> {
    /// The span of the source
    #[educe(Hash(ignore))]
    #[educe(PartialEq(ignore))]
    span: Span,
    ast_type: Option<&'a Expr<'a>>,
    name: Option<Ident<'a>>,
    body: &'a [Stmt<'a>],
}
impl<'a> Spanned for Excepthandler<'a> {
    #[inline]
    fn span(&self) -> Span {
        self.span
    }
}
#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct Arguments<'a> {
    pub posonlyargs: &'a [Arg<'a>],
    pub args: &'a [Arg<'a>],
    pub vararg: Option<&'a Arg<'a>>,
    pub kwonlyargs: &'a [Arg<'a>],
    pub kw_defaults: &'a [Expr<'a>],
    pub kwarg: Option<&'a Arg<'a>>,
    pub defaults: &'a [Expr<'a>],
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct Arg<'a> {
    pub arg: Ident<'a>,
    pub annotation: Option<&'a Expr<'a>>,
    pub type_comment: Option<&'a str>,
    #[educe(Hash(ignore))]
    #[educe(PartialEq(ignore))]
    pub span: Span,
}
impl<'a> Spanned for Arg<'a> {
    #[inline]
    fn span(&self) -> Span {
        self.span
    }
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct Keyword<'a> {
    pub arg: Option<Ident<'a>>,
    pub value: &'a Expr<'a>,
    #[educe(Hash(ignore))]
    #[educe(PartialEq(ignore))]
    pub span: Span,
}
impl<'a> Spanned for Keyword<'a> {
    #[inline]
    fn span(&self) -> Span {
        self.span
    }
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct Alias<'a> {
    pub name: Ident<'a>,
    pub asname: Option<Ident<'a>>,
    #[educe(Hash(ignore))]
    #[educe(PartialEq(ignore))]
    pub span: Span,
}
impl<'a> Spanned for Alias<'a> {
    #[inline]
    fn span(&self) -> Span {
        self.span
    }
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct WithItem<'a> {
    pub context_expr: &'a Expr<'a>,
    pub optional_vars: Option<&'a Expr<'a>>,
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub struct MatchCase<'a> {
    pub pattern: &'a Pattern<'a>,
    pub guard: Option<&'a Expr<'a>>,
    pub body: &'a [Stmt<'a>],
}

#[derive(Educe, Debug, Clone)]
#[educe(PartialEq, Eq, Hash)]
pub enum Pattern<'a> {
    MatchValue {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: &'a Expr<'a>,
    },
    MatchSingleton {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        value: Constant<'a>,
    },
    MatchSequence {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        patterns: &'a [Pattern<'a>],
    },
    MatchMapping {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        keys: &'a [Expr<'a>],
        patterns: &'a [Pattern<'a>],
        rest: Option<Ident<'a>>,
    },
    MatchClass {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        cls: &'a Expr<'a>,
        patterns: &'a [Pattern<'a>],
        kwd_attrs: &'a [Ident<'a>],
        kwd_patterns: &'a [Pattern<'a>],
    },
    MatchStar {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        name: Option<Ident<'a>>,
    },
    MatchAs {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        pattern: Option<&'a Pattern<'a>>,
        name: Option<Ident<'a>>,
    },
    MatchOr {
        /// The span of the source
        #[educe(Hash(ignore))]
        #[educe(PartialEq(ignore))]
        span: Span,
        patterns: &'a [Pattern<'a>],
    },
}
impl<'a> Spanned for Pattern<'a> {
    fn span(&self) -> Span {
        match *self {
            Pattern::MatchValue { span, .. } |
            Pattern::MatchSingleton { span, .. } |
            Pattern::MatchSequence { span, .. } |
            Pattern::MatchMapping { span, .. } |
            Pattern::MatchClass { span, .. } |
            Pattern::MatchStar { span, .. } |
            Pattern::MatchAs { span, .. } |
            Pattern::MatchOr { span, .. } => span,
        }
    }
}
#[derive(PartialEq, Eq, Hash, Debug, Clone)]
pub struct TypeIgnore<'a> {
    pub lineno: i32,
    pub tag: &'a str,
}

